### ISSUE TITLE
04/13 (수) 주요 기능 명세 논의1

### ISSUE THREAD

**Issue by json-choi** [f-lab-edu/soldout#1]
[위키 링크](https://github.com/f-lab-edu/soldout/wiki/%EA%B8%B0%EB%8A%A5%EB%AA%85%EC%84%B8-%EB%85%BC%EC%9D%98)

추후 작업리스트
- [x]  api 상세화
- [x] 프로젝트 초기 세팅

**Comment by f-lab-bright** [comment]
테스트

**Comment by f-lab-bright** [comment]
테스트

**Comment by f-lab-bright** [comment]
test

**Comment by f-lab-bright** [comment]
test
