### ISSUE TITLE
프로젝트 관련 메모장

### ISSUE THREAD

**Issue by kimcno3** [f-lab-edu/soldout#13]
### 추가 리펙토링 해야할 업무
1. 로그인 기능 구현
    - `RedisTemplate` 적용
    - `@Valid` 인증 어노테이션 구체적으로 구현
2. 상품 목록 API 구현
3. Docker-compose
    - volume 개념에 대해 알아보기

### 참고 내용
- JwtSecurityService 구현 메소드 참고 사이트 : [링크](https://devkingdom.tistory.com/113)
- 쿠키 세션 설명 : [링크](https://velog.io/@gmtmoney2357/스프링-부트-로그인-쿠키-세션#-서블릿이-제공하는-세션-기능-사용하기)
- SESSION 생명 주기 설명 : [링크](https://codevang.tistory.com/201)
- 스프링 세션 생성 시점 : [링크](https://kimfk567.tistory.com/51)
- 스프링 세션 생성 시점 2 : [링크](https://soon-devblog.tistory.com/2)
- Github Actions 기초 문법 설명 : [링크](https://velog.io/@adam2/Github-Action-%EC%A3%BC%EC%9A%94-%EB%AC%B8%EB%B2%95)
- Repo, DAO, Mapper 차이 개념 설명 : [링크](https://umbum.dev/1204?category=1062058)
- Mybatis Collection, resultMap 활용법 : [링크](https://europani.tistory.com/212)

### `Wiki`에 기재할 내용
- 로그인 인증 방식을  토큰 방식이 아닌 세션/쿠키 방식을 선택한 이유 + 추상화를 하지 않은 이유
    - 참고자료
        - 장단점 : [링크](https://tofusand-dev.tistory.com/89)
        - 쿠키/세션, 토큰 차이점 : [링크](https://velog.io/@cjung5318/쿠키-세션-토큰의-차이점)
        - Refresh Token을 활용하는 이유 : [링크](https://velog.io/@dyparkkk/spring-sequrity-jwt-사용하기access-token-refresh-token)
        - 세션 서버 과부화 해결 방법 : [링크](https://ecsimsw.tistory.com/entry/Load-Balancing%EA%B3%BC-%EC%84%B8%EC%85%98-%EC%9C%A0%EC%A7%80-Sticky-Session-Session-Clustering)
- HttpSession 객체의 선언 방법에 따른 생성
- 로그인 검증 처리 로직을 구현한 방법 → HadlerInterCeptor를 선택 & AOP를 선택하지 않은 이유
- 예외처리에 대한 책임을 서비스 레이어에 둔 이유
- (예정) 동시성 해결 문제
- (예정) 서버 과부하 해결 방법 및 선택한 이유

## 📌  프로젝트 요구사항 모음
    - **DB**
        - database는 나중에 연동
        - database를 사용하게 되면 mysql
        - database 연동을 위해서 mybatis (or jdbcTemplate)
            
            // SQL을 직접 사용해보기 위해서
            
    - **docker or docker-compose**
        
        → 로컬 개발환경 구성을 위해서 (docker-compose)
        
        → 나중에 배포과정에서 해볼 예정
        
        → DB까지 사용할 때 버전 등의 환경을 동일시하게 맞추기 위함
        
        docker desktop을 설치 하시고, mysql 8 버전의 이미지를 container로 띄워보시면 좋을 것 같네요.
        
        가능하다면 docker-compose 스크립트로도 구성을 해두시면 더욱 좋을 것 같습니다
        
        - docker desktop 설치
        - docker로 mysql 실행해보기 (mysql client로 연결해보고 sql 실행까지 잘 되는지도)
        - docker-compose 스크립트로 mysql을 구성할 수 있게 작성
            - 이거는 프로젝트 레포 안에 스크립트를 넣어두고, 프로젝트가 동작하는 과정에서 필요한 외부 서비스들을 이 스크립트 하나로 구성이 되도록 만들 예정입니다
    - **github / git**
        
        → branch 관리 정책을 사용. github flow
        
    - **CI / CD**
        
        → pr 올라오면 lint, build, test 를 자동으로 실행. github actions 사용
        
        → lint : google checkStyle 파일 설정 (완)
        
        → 실제 검사 설정은 미적용
        
    - **login 인증 방식**
        
        → session (spring-session을 이용하지 않고, 직접 구현)
        
### Use Case 명세

📌 추가 : 구매 입찰 & 판매 입찰
- 같은 사이즈의 제품에서 `구매 희망가`와 `판매 희망가`가 `동일`한 사용자가 매칭될 경우, 거래가 성사된다.

    - `판매자`는 해당 제품을 `검수 센터`에 배송한 이후, `검수과정`을 거친다.

    - 검수가 통과되면 `검수 센터`에서 해당 제품을 `구매자의 배송지`로 배송한다.

    - 구매자는 배송이 시작되면(또는 도착하면) 해당 가격으로 `결제`를 진행한다.

    - `판매자`는 구매자에게 상품 배송이 시작되면 `정산`을 진행한다.

**Comment by f-lab-bright** [comment]
redisTemplate은 어떤 곳에서 적용해 볼 수 있을까요?!

**Comment by kimcno3** [comment]
session 방식으로 로그인 기능을 구현할 경우 RedisTemplate을 활용해 로그인 회원 정보와 세션Id를 관리해볼 수 있을 것 같습니다!!
